<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.10" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.1" />
    <PackageReference Include="Core.ApplicationLayer" Version="1.0.*" />
    <PackageReference Include="Core.CrossCuttingConcernLayer" Version="1.0.*" />
    <PackageReference Include="Core.PersistenceLayer" Version="1.0.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetroMiles.ApplicationLayer\MetroMiles.ApplicationLayer.csproj" />
    <ProjectReference Include="..\MetroMiles.PersistenceLayer\MetroMiles.PersistenceLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="logs\" />
  </ItemGroup>

</Project>
