<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Auths\Commands\Create\" />
    <Folder Include="Features\Auths\Commands\Delete\" />
    <Folder Include="Features\Auths\Commands\Update\" />
    <Folder Include="Features\Auths\Queries\GetById\" />
    <Folder Include="Features\Auths\Queries\GetList\" />
    <Folder Include="Features\Auths\Rules\" />
    <Folder Include="Features\Auths\Profiles\" />
    <Folder Include="Features\Models\Commands\" />
    <Folder Include="Features\Models\Constants\" />
    <Folder Include="Features\Models\Rules\" />
    <Folder Include="Features\Users\Commands\Delete\" />
    <Folder Include="Features\Users\Commands\Update\" />
    <Folder Include="Features\Users\Queries\GetById\" />
    <Folder Include="Features\Users\Queries\GetList\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Core.ApplicationLayer" Version="1.0.0" />
    <PackageReference Include="Core.CrossCuttingConcernLayer" Version="1.0.0" />
    <PackageReference Include="Core.PersistenceLayer" Version="1.0.0" />
    <PackageReference Include="Core.SecurityLayer" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MetroMiles.DomainLayer\MetroMiles.DomainLayer.csproj" />
  </ItemGroup>

</Project>
